"""This migration adds deadline and description fields to the Task model."""

# Generated by Django 5.2.3 on 2025-06-20 07:42
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add deadline and description fields to Task model."""

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
