"""Migration to add List model and link it to Task model."""

# Generated by Django 5.2.3 on 2025-06-20 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add List model and link it to Task model."""

    dependencies = [
        ("tasks", "0002_task_deadline_task_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.list",
            ),
        ),
    ]
