"""Migration to add SubTask model."""

# Generated by Django 5.2.3 on 2025-06-20 11:31
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add SubTask model."""

    dependencies = [
        ("tasks", "0003_list_task_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("assignee", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("In Review", "In Review"),
                            ("Completed", "Completed"),
                            ("On Hold", "On Hold"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
