# Generated by Django 5.2.3 on 2025-06-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_subtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="assignee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
