# Generated by Django 5.2.3 on 2025-06-25 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_subtask_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
